[bitnami/jasperreports] fix valid SMTP protocols.
bitnami/containers pull request #10734
Opened 2022-10-19 14:06 UTC by schakko

### Description of the change

Previously, "tls" and "ssl" have been valid configuration parameters for the SMTP protocol. Both have not been valid from the view of Jasper and Java for years. This patch drops "tls" and "ssl" and replaces the valid values with "smtp" and "smtps". The content of this patch had been previously discussed in https://github.com/bitnami/bitnami-docker-jasperreports/issues/112.

In addition to that, TLS 1.2 or newer is enforced for TLS encrypted connections.

### Benefits

- Allow SMTPS and TLS 1.2

### Possible drawbacks

Hopefully, none.

### Applicable issues

  - fixes https://github.com/bitnami/bitnami-docker-jasperreports/issues/112

2022-10-20 10:41 UTC, dgomezleon requested changes
Thanks for contributing. The changes look good and I just required some minor changes.

2022-10-20 10:41 UTC, dgomezleon commented on bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +        # @see bitnami/bitnami-docker-jasperreports/#112: 'smtp' and 'smtps' are the only valid values
```suggestion
        #  'smtp' and 'smtps' are the only valid values (see issue [#112](https://github.com/bitnami/bitnami-docker-jasperreports/#112)).
```

2022-10-20 10:41 UTC, dgomezleon commented on bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +                # add a new prop node with mail.smtp.ssl.protocols=TLSv1.2
```suggestion
                # Add a new prop node with mail.smtp.ssl.protocols=TLSv1.2 (see issue [#112](https://github.com/bitnami/bitnami-docker-jasperreports/#112)).
```

2022-10-22 12:43 UTC, schakko commented on bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +                # add a new prop node with mail.smtp.ssl.protocols=TLSv1.2
@dgomezleon fixed in latest push

2022-10-22 12:43 UTC, schakko commented on bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +        # @see bitnami/bitnami-docker-jasperreports/#112: 'smtp' and 'smtps' are the only valid values
@dgomezleon fixed in latest push

2022-10-24 10:45 UTC, dgomezleon approved these changes
LGTM

2022-10-24 10:45 UTC, merged