[bitnami/redis-cluster] perf: add cluster-announce port and bus-port
bitnami/containers pull request #12104
Opened 2022-11-01 06:41 UTC by wojiushixiaobai

### Description of the change

Add cluster-announce-port and cluster-announce-bus-port to allow users to run redis clusters on a single node.

`REDIS_CLUSTER_ANNOUNCE_IP`
`REDIS_CLUSTER_ANNOUNCE_PORT`
`CLUSTER_ANNOUNCE_BUS_PORT`

2022-11-01 08:49 UTC, carrodher commented
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

2022-11-14 11:54 UTC, fmulero requested changes
Hi @wojiushixiaobai Thank you so much for your contribution.

Could you fix the variable names and add them to [redis-cluster-env.sh](https://github.com/bitnami/containers/blob/d89f4850bb03e8ec945da186e0e6364373b9e4a0/bitnami/redis-cluster/7.0/debian-11/rootfs/opt/bitnami/scripts/redis-cluster-env.sh#L130) files?

2022-11-14 11:54 UTC, fmulero commented on bitnami/redis-cluster/7.0/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    if ! is_empty_value "$CLUSTER_ANNOUNCE_BUS_PORT"; then
```suggestion
    if ! is_empty_value "$REDIS_CLUSTER_ANNOUNCE_BUS_PORT"; then
```

2022-11-14 11:54 UTC, fmulero commented on bitnami/redis-cluster/6.2/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh
> +    if ! is_empty_value "$CLUSTER_ANNOUNCE_BUS_PORT"; then
```suggestion
    if ! is_empty_value "$REDIS_CLUSTER_ANNOUNCE_BUS_PORT"; then
```

2022-11-14 12:45 UTC, wojiushixiaobai commented
Sorry, I think I blew it up.
I'll open a new request.

2022-11-14 12:45 UTC, closed without merging