[Odoo] Refine directory permissions for app persistence
bitnami/containers pull request #17885
Opened 2022-12-23 07:13 UTC by tobru

### Description of the change

This change refines the directory permissions of the application directory so that the image runs properly on configurations with tight permissions, like OpenShift.

### Benefits

Image works out-of-the box on OpenShift.

### Possible drawbacks

None to my knowledge.

### Applicable issues

  - fixes #17806

### Additional information

The change is also documented in the official [OpenShift documentation](https://docs.openshift.com/container-platform/4.11/openshift_images/create-images.html#images-create-guide-openshift_create-images).

2023-01-04 09:47 UTC, fmulero requested changes
Great! Thanks a lot Tobias

I reproduced your issue and this solution works perfectly. I'd prefer to move this change to the [postunpack.sh script](https://github.com/bitnami/containers/blob/cc2d38cfee4433170c5f3f999ef3f57ee9f7039d/bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo/postunpack.sh), because there we usually  tune the permission for each product. If you apply for example the following suggestion in that file, your issue should be fixed:

```diff
diff --git a/bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo/postunpack.sh b/bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo/postunpack.sh
index 06ec22cf136..0e4383b90e0 100755
--- a/bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo/postunpack.sh
+++ b/bitnami/odoo/16/debian-11/rootfs/opt/bitnami/scripts/odoo/postunpack.sh
@@ -29,9 +29,8 @@ for dir in "$ODOO_ADDONS_DIR" "$ODOO_CONF_DIR" "$ODOO_DATA_DIR" "$ODOO_LOGS_DIR"
     configure_permissions_ownership "$dir" -d "775" -f "664" -u "$ODOO_DAEMON_USER" -g "root"
 done
 
-# Use daemon user ownership for compatibility when running as a non-root user
-chown "$ODOO_DAEMON_USER" "$ODOO_BASE_DIR"
-
+# Use daemon user ownership and allow group writes for compatibility when running as a non-root user
+configure_permissions_ownership "$ODOO_BASE_DIR" -d "775" -u "$ODOO_DAEMON_USER" -g "root"
 # Create folders that existed in previous versions of this image with proper permissions/ownership
 # TODO: Remove this block in a future release
 ensure_dir_exists "${ODOO_BASE_DIR}/odoo"
```

2023-01-19 07:37 UTC, tobru commented
@fmulero Thanks for your review and testing. Would you be able to do the enhancement to `postunpack.sh`, or should I create a new PR for it?

2023-01-20 08:24 UTC, fmulero commented
> @fmulero Thanks for your review and testing. Would you be able to do the enhancement to `postunpack.sh`, or should I create a new PR for it?

If you can do it, please carry on this PR. This is a good contribution and you deserve the credit for resolving this issue.

2023-02-06 13:48 UTC, tobru commented
Keep this PR fresh, I really try to get it done

2023-02-22 21:58 UTC, verilyst commented
@tobru thank you for suggesting this PR. Are you able to address the changes suggested by @fmulero ? Otherwise, we may submit an identical Merge Request since this is a current bug/blocker for our implementation. Let us know!

2023-02-23 08:57 UTC, tobru commented
@verilyst Thanks for asking. I haven't managed to let that one bubble up in my todolist. So if you're able to create a PR, I'd be very happy.

2023-03-30 03:04 UTC, closed without merging