[bitnami/cassandra] add env for setting auto_snapshot_ttl
bitnami/containers pull request #19761
Opened 2023-01-10 13:30 UTC by nevlkv

PR on[ issue](https://github.com/bitnami/containers/issues/19750)

2023-02-01 08:31 UTC, nevlkv commented
@mdhont, need review

2023-02-02 16:25 UTC, mdhont commented
I'm running some final tests. I'll notify you soon.

2023-02-07 15:57 UTC, mdhont requested changes

2023-02-07 15:57 UTC, mdhont commented on bitnami/cassandra/4.1/debian-11/rootfs/opt/bitnami/scripts/libcassandra.sh
> +       print_validation_error "CASSANDRA_AUTO_SNAPSHOT_TTL accepted units: d (days), h (hours) or m (minutes)"
Could you fix the indentation?

```suggestion
        print_validation_error "CASSANDRA_AUTO_SNAPSHOT_TTL accepted units: d (days), h (hours) or m (minutes)"
```

2023-02-09 15:09 UTC, mdhont approved these changes
Lgtm! Thanks for contributing.

2023-02-09 15:10 UTC, merged