[bitnami/redis] Added support for hostname announcement in cluster setup #26824
bitnami/containers pull request #26832
Opened 2023-03-09 18:39 UTC by deveshk0

### Description of the change

Adds following environment variable to enable support for hostname announcement in cluster setup.

```
REDIS_CLUSTER_ANNOUNCE_HOSTNAME
REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE
```

### Benefits

- Allows cluster announcement on hostname instead of Pod IP.
- Enables smooth tls enabled cluster

### Possible drawbacks

none

### Applicable issues

- fixes #23244

### Additional information

None

2023-03-13 19:47 UTC, deveshk0 commented
@carrodher @gongomgra any update here?

2023-03-14 10:11 UTC, gongomgra commented
HI @deveshk0,

Thanks for your contribution, and sorry for the delay. We are reviewing your changes and will get back to you as soon as possible.

2023-03-14 10:34 UTC, gongomgra requested changes

2023-03-14 10:34 UTC, gongomgra commented on bitnami/redis-cluster/README.md
> +| `REDIS_CLUSTER_ANNOUNCE_HOSTNAME`       | Hostname that node should announce, used for non dynamic ip environents.
There's a minor typo here `environents` -> `environments`.

2023-03-14 11:02 UTC, deveshk0 commented on bitnami/redis-cluster/README.md
> +| `REDIS_CLUSTER_ANNOUNCE_HOSTNAME`       | Hostname that node should announce, used for non dynamic ip environents.
Thanks @gongomgra  Updated

2023-03-15 12:41 UTC, gongomgra approved these changes
LGTM!

2023-03-15 12:41 UTC, gongomgra commented
Thanks @deveshk0 for your contribution. I'm merging your changes now.

2023-03-15 12:41 UTC, merged