[bitnami/*] Standarize initial testing suites
bitnami/containers pull request #27521
Opened 2023-03-17 11:25 UTC by FraPazGal

### Description of the change

Updates the first testing suites to the latest standards:

- Added new `check-spdx` test
- Every component added to the container now has its binary checked
- Removes the use of `{{ .Vars.root_dir }}` from the asset-specific tests

### Benefits

Homogeneous testing suites across the whole repository

### Possible drawbacks

None

2023-03-17 12:22 UTC, mdhont submitted a review, later dismissed
Lgtm!

2023-03-17 15:53 UTC, joancafom requested changes
Thanks for your PR! I left a small comment

2023-03-17 15:53 UTC, joancafom commented on .vib/apache/goss/goss.yaml
> +  ../../common/goss/templates/check-sdpx.yaml: {}
This is actually `spdx`
```suggestion
  ../../common/goss/templates/check-sdpx.yaml: {}
```

2023-03-17 16:21 UTC, FraPazGal commented on .vib/apache/goss/goss.yaml
> +  ../../common/goss/templates/check-sdpx.yaml: {}
Thanks! Typo fixed

2023-03-20 10:47 UTC, joancafom approved these changes
LGTM!

2023-03-21 08:23 UTC, merged