[bitnami/mongodb] Add MongoDB container VIB tests
bitnami/containers pull request #27806
Opened 2023-03-20 15:59 UTC by mdhont

The main objective of this PR is to publish our Bitnami MongoDB container using VMware Image Builder. In order to do that, several changes are included:

Increasing the existing test coverage of the asset by adding Goss tests.
Update verify and publish VIB pipeline's definitions.

### Benefits

Ensuring higher quality of the container catalog.
Increased pool of assets completely handled by VMware Image Builder.

### Possible drawbacks

Automated tests could introduce additional flakiness to the CI/CD.

2023-03-23 12:04 UTC, joancafom requested changes
Thanks for your PR! I left you some comments as a review

2023-03-23 12:04 UTC, joancafom commented on .vib/mongodb/goss/mongodb.yaml
> +file:
You should check `/opt/bitnami/mongodb/conf/mongodb.conf` and some of its rendered content

2023-03-24 12:55 UTC, FraPazGal requested changes
Hi @mdhont, please review my comments when you can. There is a couple of things I have concerns about.

2023-03-27 12:08 UTC, joancafom requested changes

2023-03-27 12:08 UTC, joancafom commented on .vib/mongodb/goss/vars.yaml
> +  - paths:
You are not checking the permissions

2023-03-27 12:08 UTC, joancafom commented on .vib/mongodb/goss/vars.yaml
> +    - /opt/bitnami/mongodb/conf/mongodb.conf
This is already checked in the `mongodb.yaml` file

2023-03-27 12:08 UTC, joancafom commented on bitnami/mongodb/5.0/debian-11/Dockerfile
> +## Install required system packages and dependencies
Remove the trigger files once the PR is marked as ready for review

2023-03-27 12:08 UTC, joancafom commented on .vib/mongodb/goss/mongodb.yaml
> +      - /port.*{{ .Vars.port }}/
Don't use vars here, use the raw value instead as it is unlikely to change.

2023-03-27 12:08 UTC, joancafom commented on .vib/mongodb/goss/mongodb.yaml
> +      - /path.*\/opt\/bitnami\/mongodb\/logs\/mongodb.log/
The `/` character does not need to be escaped

2023-03-27 12:08 UTC, joancafom commented on .vib/mongodb/goss/vars.yaml
> +port: 27017
Remove this line

2023-03-28 11:20 UTC, FraPazGal commented on .vib/mongodb/goss/mongodb.yaml
> +      - This solution ships the official MongoDB Community binaries
Minor comment, I think checking for such a long string is very error-prone if upstream decides to change some of it.

```suggestion
      - official MongoDB Community
```

2023-03-28 12:15 UTC, joancafom commented on .vib/mongodb/goss/mongodb.yaml
> +      - official MongoDB Community
Please, add back the whole string again. This is not something we get from upstream, but we add it ourselves

2023-03-28 13:58 UTC, joancafom approved these changes
LGTM!

2023-03-28 14:12 UTC, FraPazGal approved these changes
LGTM!

2023-03-28 14:34 UTC, merged