[bitnami/airflow-scheduler] Add airflow-scheduler tests
bitnami/containers pull request #31098
Opened 2023-04-20 14:53 UTC by mdhont

### Description of the change

The main objective of this PR is to publish our Bitnami NGINX Exporter container using VMware Image Builder. In order to do that, several changes are included:

- Increasing the existing test coverage of the asset by adding Goss tests.
- Update verify and publish VIB pipeline's definitions.

### Benefits

- Ensuring higher quality of the container catalog.
- Increased pool of assets completely handled by VMware Image Builder.

### Possible drawbacks

- Automated tests could introduce additional flakiness to the CI/CD.

### Applicable issues

NA

Tested in:

Recent action run: https://github.com/bitnami/containers/actions/runs/4723973349

2023-05-05 14:09 UTC, joancafom reviewed
This PR is much similar to the one for Airflow you opened. I have already provide feedback there, please take a look and apply it here as well.

2023-05-17 10:50 UTC, agomezmoron submitted a review, later dismissed

2023-05-17 13:57 UTC, joancafom requested changes

2023-05-22 07:17 UTC, joancafom approved these changes

2023-05-22 11:13 UTC, merged