[bitnami/airflow-worker] Add VIB tests
bitnami/containers pull request #31100
Opened 2023-04-20 15:20 UTC by mdhont

### Description of the change

The main objective of this PR is to publish our Bitnami airflow-worker container using VMware Image Builder. In order to do that, several changes are included:

- Increasing the existing test coverage of the asset by adding Goss tests.
- Update verify and publish VIB pipeline's definitions.

### Benefits

- Ensuring higher quality of the container catalog.
- Increased pool of assets completely handled by VMware Image Builder.

### Possible drawbacks

Automated tests could introduce additional flakiness to the CI/CD.

### Applicable issues

NA

2023-05-05 14:18 UTC, joancafom reviewed
This PR is much similar to the one for Airflow you've opened. I have already provided feedback there, please take a look and apply it here as well.

2023-05-17 12:00 UTC, agomezmoron approved these changes

2023-05-17 12:00 UTC, agomezmoron submitted a review, later dismissed

2023-05-17 14:00 UTC, joancafom requested changes

2023-05-17 14:00 UTC, joancafom commented on .vib/airflow-worker/goss/airflow-worker.yaml
> +      - virtualenv
As performed in the main Airflow PR, please reduce the number of packages and move them to the vars.yaml file.

2023-05-22 07:21 UTC, joancafom approved these changes

2023-05-22 11:14 UTC, merged