[bitnami/ghost] Add Ghost vib tests
bitnami/containers pull request #31589
Opened 2023-04-25 09:27 UTC by mdhont

Signed-off-by: mdhont [michield@vmware.com](michield@vmware.com)

### Description of the change

The main objective of this PR is to publish our Bitnami Ghost container using VMware Image Builder. In order to do that, several changes are included:

- Increasing the existing test coverage of the asset by adding Goss tests.
- Update verify and publish VIB pipeline's definitions.

### Benefits

- Ensuring higher quality of the container catalog.
- Increased pool of assets completely handled by VMware Image Builder.

### Possible drawbacks

Automated tests could introduce additional flakiness to the CI/CD.

### Applicable issues

NA

### Additional information

Successful test run:
https://github.com/bitnami/containers/actions/runs/4798845018/jobs/8537675935

2023-05-08 15:04 UTC, joancafom commented on .vib/ghost/goss/ghost.yaml
> +    mode: "0755"
I'd avoid this check too. I don't think it adds much value and the path has many hardcoded versions which will be hard to maintain.

2023-05-08 15:38 UTC, mdhont commented on .vib/ghost/goss/vars.yaml
> +      - /opt/bitnami/ghost
The permissions for "/opt/bitnami/ghost" do not seem to be explicitly set, (using the numerical notation I mean) so the test fails. (Permissions of that folder are 0777).

2023-05-17 14:09 UTC, joancafom commented on .vib/ghost/goss/vars.yaml
> +      - /opt/bitnami/ghost
The permissions of `/opt/bitnami/ghost` are explicitly set:

https://github.com/bitnami/containers/blob/6d597b976a0dbb9f10329820ef5f80cb75618d77/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/ghost/postunpack.sh#L43

Moreover, the check should work:

```bash
$ stat $GHOST_BASE_DIR
  File: /opt/bitnami/ghost
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 8dh/141d	Inode: 4073330     Links: 6
Access: (0777/drwxrwxrwx)  Uid: (  999/ UNKNOWN)   Gid: (    0/   ghost)
Access: 2023-05-17 14:04:41.896760757 +0000
Modify: 2023-05-17 13:07:34.000000000 +0000
Change: 2023-05-17 14:04:41.807761876 +0000
 Birth: 2023-05-17 14:04:25.346846632 +0000
```

2023-05-17 14:15 UTC, joancafom requested changes

2023-05-17 14:15 UTC, joancafom commented on .vib/ghost/goss/vars.yaml
> +    - /opt/bitnami/ghost
The permissions of `/opt/bitnami/ghost` are explicitly set:

https://github.com/bitnami/containers/blob/6d597b976a0dbb9f10329820ef5f80cb75618d77/bitnami/ghost/5/debian-11/rootfs/opt/bitnami/scripts/ghost/postunpack.sh#L43

Moreover, the check should work:

```bash
$ stat $GHOST_BASE_DIR
  File: /opt/bitnami/ghost
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 8dh/141d	Inode: 4073330     Links: 6
Access: (0777/drwxrwxrwx)  Uid: (  999/ UNKNOWN)   Gid: (    0/   ghost)
Access: 2023-05-17 14:04:41.896760757 +0000
Modify: 2023-05-17 13:07:34.000000000 +0000
Change: 2023-05-17 14:04:41.807761876 +0000
 Birth: 2023-05-17 14:04:25.346846632 +0000
```

2023-05-22 07:39 UTC, joancafom approved these changes

2023-05-22 11:15 UTC, merged