[bitnami/opencart] Add VIB tests
bitnami/containers pull request #33593
Opened 2023-05-12 10:35 UTC by marcosbc

### Description of the change

The main objective of this PR is to publish our Bitnami OpenCart container using VMware Image Builder. In order to do that, several changes are included:

* Increasing the existing test coverage of the asset by adding Goss tests.
* Update verify and publish VIB pipeline's definitions.

### Benefits

* Ensuring higher quality of the container catalog.
* Increased pool of assets completely handled by VMware Image Builder.

### Possible drawbacks

Automated tests could introduce additional flakiness to the CI/CD.

### Applicable issues

N/A

2023-05-15 13:10 UTC, migruiz4 requested changes
Thank you for your contribution! Could you please take a look at my comments?

2023-05-15 13:29 UTC, marcosbc commented on .vib/opencart/goss/vars.yaml
> +  - zlib
Well, those are the requirements according to the official documentation. In the case of required PHP extensions, I would add those even if we are not explicitly adding them in the `postunpack` logic. If not, we would not be able to keep up with the references.

2023-05-15 13:29 UTC, marcosbc commented on .vib/opencart/goss/opencart.yaml
> +command:
The `upload` folder is the root directory for all OpenCart files. That is why it is not present in the image. We simply move all those files to `/opt/bitnami/opencart`. There isn't much we can check there.

2023-05-24 08:37 UTC, migruiz4 requested changes
Looks good to me, could you please remove the trigger?

2023-05-24 10:21 UTC, marcosbc commented
Done @migruiz4!

2023-05-24 12:48 UTC, migruiz4 approved these changes

2023-05-24 14:08 UTC, merged