[bitnami/containers] Automate license checks
bitnami/containers pull request #39442
Opened 2023-06-30 12:12 UTC by rloporp

### Description of the change

Licenses and copyright notices are included as headers in all our public repositories.
We'll automatically check license headers with the [SkyWalking Eyes](https://github.com/apache/skywalking-eyes) GitHub action.

### Benefits

Automatic license compliance.

### Possible drawbacks

No known drawbacks.

### Applicable issues

None.

2023-07-01 11:09 UTC, carrodher commented on .github/workflows/license-headers.yml
> +name: license-headers
We usually add a prefix to order the actions (i.e `[CI/CD] ...`, `[Support] ...`, etc) and a descriptive title

What do you think about using something like this?
```suggestion
name: [License] Check license headers
```

2023-07-03 07:51 UTC, carrodher submitted a review, later dismissed
LGTM

2023-07-03 08:46 UTC, gongomgra requested changes

2023-07-03 09:46 UTC, rloporp commented on .licenserc.yaml
> +    - "**/Dockerfile"
I agree we should double-check several other files, but we're limiting the scope to Dockerfiles in this first iteration.

2023-07-03 09:47 UTC, gongomgra commented on .licenserc.yaml
> +    - "**/Dockerfile"
Perfect then, thanks for the clarification!

2023-07-03 09:47 UTC, gongomgra submitted a review, later dismissed

2023-07-03 11:20 UTC, carrodher approved these changes

2023-07-03 12:22 UTC, merged