[bitnami/wildfly] Deprecate Wildfly 26
bitnami/containers pull request #46956
Opened 2023-09-01 13:03 UTC by corico44

### Description of the change

Deprecate Wildfly 26 branch.

2023-09-03 10:13 UTC, carrodher submitted a review, later dismissed

2023-09-04 07:56 UTC, fmulero approved these changes
LGTM

2023-09-04 07:57 UTC, fmulero requested changes
Please resolve conflicts

2023-09-04 10:50 UTC, fmulero approved these changes

2023-09-04 10:54 UTC, closed without merging