[bitnami/redis-cluster] Support scenario where IPs are reused
bitnami/containers pull request #4990
Opened 2022-09-02 13:21 UTC by avcad

### Description of the change

Discussion https://github.com/bitnami/charts/issues/11341

### Benefits
There is a bug in that if a redis-cluster is restarted, and the redis node starting is assigned the same IP that was used by one of the shutdown nodes, the existing logic incorrectly updates the IPs.

For example:
Shut down cluster:
```
redis-0   127.0.0.1
redis-1   127.0.0.2
```
new IPs:
```
redis-0   127.0.0.2
redis-2   127.0.0.1
```
The existing logic results in:
a) switch 127.0.0.1 to 127.0.0.2
a) switch 127.0.0.2 to 127.0.0.1 (bug)
```
redis-0   127.0.0.1
redis-1   127.0.0.1
```
The update logic ensures that newly set IPs are not updated again

2022-09-02 13:23 UTC, avcad commented
@carrodher

2022-09-05 16:12 UTC, dgomezleon requested changes
Just a minor request.

2022-09-05 16:12 UTC, dgomezleon commented on bitnami/redis-cluster/6.2/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh
> +        sed -i "s/<NEWIP>//g" "${REDIS_DATA_DIR}/nodes.conf"
We have a method called `replace_in_file` for this. 

Could you please use it to avoid issues with `sed`?

2022-09-06 08:02 UTC, dgomezleon approved these changes
LGTM

2022-09-06 08:05 UTC, merged