Patching the Gaps: Essential Kibana Configurations added
bitnami/containers pull request #53871
Opened 2023-12-15 19:44 UTC by muhammeddanish

### Description of the change

This pull request integrates five essential Kibana configurations into our Docker image, enhancing functionality and performance:
1. [server.publicBaseUrl](https://www.elastic.co/guide/en/kibana/8.11/settings.html#server-publicBaseUrl)
2. [xpack.security.encryptionKey](https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html#security-configure-settings)
3. [xpack.reporting.encryptionKey](https://www.elastic.co/guide/en/kibana/8.11/reporting-settings-kb.html#encryption-keys)
4. [elasticsearch.requestTimeout](https://www.elastic.co/guide/en/kibana/8.11/settings.html#elasticsearch-requestTimeout)
5. [newsfeed.enabled](https://www.elastic.co/guide/en/kibana/8.11/settings.html)

### Benefits

This PR unlocks further Kibana customization possibilities by adding five essential configurations.
### Possible drawbacks

Without this update, Kibana in versions 7 and above won't work properly with custom domain names (DNS) due to the missing server.publicBaseUrl setting. Other changes enhance its overall functionality.

### Applicable issues

By adding five key configurations, this PR opens doors to enhanced Kibana customization and fixes the issue of DNS access outlined in https://stackoverflow.com/questions/66634552/cant-access-kibana-with-domain.

DNS access for Kibana is now enabled by adding the server.publicBaseUrl configuration, a must for versions 7.x and above.

2023-12-17 12:31 UTC, carrodher commented
Thanks for your contribution. Please note the version bump from `8.11.3` to `8.11.4` since this version is the upstream Kibana version which at this moment, the latest one is `8.11.3`, see https://github.com/elastic/kibana/releases.

Could you please revert any change related to this version bump?

2023-12-17 18:59 UTC, muhammeddanish commented
> Thanks for your contribution. Please note the version bump from `8.11.3` to `8.11.4` since this version is the upstream Kibana version which at this moment, the latest one is `8.11.3`, see https://github.com/elastic/kibana/releases.
> 
> Could you please revert any change related to this version bump?

Thanks @carrodher for the prompt response, I am not sure of how the versioning works in bitnami container images :) 

As recommended, I have removed the modified bump.

2023-12-18 11:56 UTC, dgomezleon requested changes

2023-12-18 11:56 UTC, dgomezleon commented on bitnami/kibana/8/debian-11/rootfs/opt/bitnami/scripts/kibana-env.sh
> +export ELASTICSEARCH_REQUESTTIMEOUT="$KIBANA_ELASTICSEARCH_REQUESTTIMEOUT"
From my understanding, these variables are only for Kibana, so you only need to add this:

```
export KIBANA_SERVER_PUBLICBASEURL="${KIBANA_SERVER_PUBLICBASEURL:-}"
export KIBANA_XPACK_SECURITY_ENCRYPTIONKEY="${KIBANA_XPACK_SECURITY_ENCRYPTIONKEY:-}"
export KIBANA_XPACK_REPORTING_ENCRYPTIONKEY="${KIBANA_XPACK_REPORTING_ENCRYPTIONKEY:-}"
export KIBANA_NEWSFEED_ENABLED="${KIBANA_NEWSFEED_ENABLED:-true}"
export KIBANA_ELASTICSEARCH_REQUESTTIMEOUT="${KIBANA_ELASTICSEARCH_REQUESTTIMEOUT:-30000}"
```

2023-12-18 11:56 UTC, dgomezleon commented on bitnami/kibana/8/debian-11/rootfs/opt/bitnami/scripts/libkibana.sh
> +
All this block applies only for Kibana, so I would suggest this change:

```
        # Kibana override configuration
        if [[ "$SERVER_FLAVOR" = "kibana" ]]; then
            if is_boolean_yes "$KIBANA_DISABLE_STRICT_CSP"; then
                kibana_conf_set "csp.strict" "false" "bool"
            fi
            if ! is_empty_value "$KIBANA_SERVER_PUBLICBASEURL"; then
                kibana_conf_set "server.publicBaseUrl" "$KIBANA_SERVER_PUBLICBASEURL"
            fi
            if ! is_empty_value "$KIBANA_XPACK_SECURITY_ENCRYPTIONKEY"; then
                kibana_conf_set "xpack.security.encryptionKey" "$KIBANA_XPACK_SECURITY_ENCRYPTIONKEY"
            fi
            if ! is_empty_value "$KIBANA_XPACK_REPORTING_ENCRYPTIONKEY"; then
                kibana_conf_set "xpack.reporting.encryptionKey" "$KIBANA_XPACK_REPORTING_ENCRYPTIONKEY"
            fi
            if ! is_boolean_yes "$KIBANA_NEWSFEED_ENABLED"; then
                kibana_conf_set "newsfeed.enabled" "false" "bool"
            fi
            if [[ "$KIBANA_ELASTICSEARCH_REQUESTTIMEOUT" != "30000" ]]; then
                kibana_conf_set "elasticsearch.requestTimeout" "$KIBANA_ELASTICSEARCH_REQUESTTIMEOUT"
            fi
        fi
```

2023-12-18 12:22 UTC, dgomezleon commented
Hi @muhammeddanish,

Thanks for contributing! 
I have added some comments to the PR. Also, please note this should also be applied to branch 7.

2023-12-18 12:48 UTC, muhammeddanish commented
> Hi @muhammeddanish,
> 
> Thanks for contributing! I have added some comments to the PR. Also, please note this should also be applied to branch 7.

Thanks @dgomezleon !!
I have updated the code with the suggested changes.

2023-12-18 15:52 UTC, dgomezleon approved these changes
LGTM

2023-12-19 05:18 UTC, muhammeddanish commented
> LGTM

Thank you :)  

Could you please help me to merge this PR?

2023-12-19 07:31 UTC, merged