add envsubst to kubectl image
bitnami/containers pull request #55365
Opened 2024-01-26 12:49 UTC by djschny

### Description of the change

This changes adds `envsubst` to the `kubectl` image.

### Benefits

This helps when using using kubernetes manifests that have values that change depending upon the environment situation.
It is fairly common to do something like the following:

```
export SERVER_URL="my-prod-server"
envsubst < my-manifest.yaml | kubectl apply -f -
```

### Possible drawbacks

It increases the image size a bit (I believe about 100K).

### Applicable issues

### Additional information

This was already done/raised for #34957

2024-01-31 16:24 UTC, gongomgra requested changes

2024-01-31 16:24 UTC, gongomgra commented on bitnami/kubectl/1.26/debian-11/Dockerfile
> +    apt-get -y install gettext-base && \
You can add the required packages to the `install_packages` directive at line 26

2024-01-31 16:28 UTC, gongomgra commented
Hi @djschny,

Apart from the comment I added here, I will create a new internal task to verify the availability of this package in the rest of the distributions we offer as part of the [Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog). 

In the meantime, we recommend you to extend our base image with your required `RUN` action to install the `gettext-base` package.

2024-02-20 23:23 UTC, djschny commented
Requested changes made.

2024-04-01 12:27 UTC, djschny commented
@gongomgra is there anything else I need to change to get this moving?

2024-04-02 07:24 UTC, gongomgra commented
Hi @djschny,

Sorry for the delay. I have been checking this and I have found we are adding the `gettext` package instead of `gettext-base` in other images like [appsmith](https://github.com/bitnami/containers/blob/main/bitnami/appsmith/1/debian-12/Dockerfile#L26). Can you please update your PR? I don't have any other suggestion/requirement to this.

2024-04-02 07:47 UTC, gongomgra requested changes
Please also fix the conflicts with main branch

2024-04-02 07:47 UTC, gongomgra commented on bitnami/kubectl/1.26/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl git jq procps gettext-base
Please use `gettext` as in other images like [appsmith](https://github.com/bitnami/containers/blob/main/bitnami/appsmith/1/debian-12/Dockerfile#L26)

2024-04-02 08:10 UTC, gongomgra commented on bitnami/kubectl/1.26/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl git jq procps gettext-base
```suggestion
RUN install_packages ca-certificates curl gettext git jq procps
```

2024-04-02 08:10 UTC, gongomgra commented on bitnami/kubectl/1.27/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl git jq procps gettext-base
```suggestion
RUN install_packages ca-certificates curl gettext git jq procps
```

2024-04-02 08:10 UTC, gongomgra commented on bitnami/kubectl/1.28/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl git jq procps gettext-base
```suggestion
RUN install_packages ca-certificates curl gettext git jq procps
```

2024-04-02 08:10 UTC, gongomgra commented on bitnami/kubectl/1.29/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl git jq procps gettext-base
```suggestion
RUN install_packages ca-certificates curl gettext git jq procps
```

2024-04-02 08:22 UTC, closed without merging

2024-04-02 08:22 UTC, gongomgra commented
Sorry @djschny, I have just noticed your changes are for an old version of the Dockerfiles based on debian-11, but we have recently updated the base image to debian-12. I have added the `gettext` package for the next image revision, so I'm closing this PR. Sorry for the inconveniences.

2024-04-02 09:21 UTC, gongomgra commented
New images have been released including the `gettext` system package

https://github.com/bitnami/containers/tree/main/bitnami/kubectl/1.27/debian-12