add `envsubst` to `nginx` and `kubectl` images
bitnami/containers pull request #55361
Opened 2024-01-25 19:10 UTC by djschny

### Description of the change

Addresses #34957

### Benefits

Documented in associated issue.

### Possible drawbacks

Documented in associated issue.

### Applicable issues

Fixes #34957

### Additional information

2024-01-25 19:22 UTC, djschny commented
Switching from draft to regular PR to see if builds will run.

2024-01-26 08:51 UTC, javsalgar commented
Hi!

Thank you so much for the PR. The verification is not being triggered because of this

```
Changes should affect to only one asset. You are currently modifying: kubectl nginx
```

Could you split the PR for `kubectl` and `nginx`?

2024-01-26 11:44 UTC, djschny commented
> Could you split the PR for kubectl and nginx?

Sure, sorry didn't realize that.

2024-01-26 12:10 UTC, djschny commented
@javsalgar all fixed, should be good to go now on this one, will open a second PR.

2024-01-31 16:43 UTC, gongomgra commented
Hi @djschny,

As mentioned in #55365 , we have created an internal task to evaluate the `gettext-base` package addition in all distributions in which we provide NGINX images as part of [Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog). We will keep you posted.

In the meantime, please extend our image with the required packages on your side.

2024-02-20 23:23 UTC, djschny commented
Requested changes done.

2024-04-01 12:27 UTC, djschny commented
@gongomgra is there anything else I need to change to get this moving?

2024-04-02 07:24 UTC, gongomgra commented
Hi @djschny,

Sorry for the delay. I have been checking this and I have found we are adding the `gettext` package instead of `gettext-base` in other images like [appsmith](https://github.com/bitnami/containers/blob/main/bitnami/appsmith/1/debian-12/Dockerfile#L26). Can you please update your PR? I don't have any other suggestion/requirement to this.

2024-04-02 07:47 UTC, gongomgra requested changes
Please also fix the conflicts with main branch

2024-04-02 07:47 UTC, gongomgra commented on bitnami/nginx/1.24/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl libcrypt1 libgeoip1 libpcre3 libssl1.1 openssl procps zlib1g gettext-base
Please use `gettext` as in other images like [appsmith](https://github.com/bitnami/containers/blob/main/bitnami/appsmith/1/debian-12/Dockerfile#L26)

2024-04-02 08:14 UTC, jotamartos commented on bitnami/nginx/1.25/debian-11/Dockerfile
> +RUN install_packages ca-certificates curl libcrypt1 libgeoip1 libpcre3 libssl1.1 openssl procps zlib1g gettext-base
```suggestion
RUN install_packages ca-certificates curl gettext libcrypt1 libgeoip1 libpcre3 libssl1.1 openssl procps zlib1g
```

2024-04-02 08:22 UTC, gongomgra commented
Sorry @djschny, I have just noticed your changes are for an old version of the Dockerfiles based on debian-11, but we have recently updated the base image to debian-12. I have added the `gettext` package for the next image revision, so I'm closing this PR. Sorry for the inconveniences.

2024-04-02 08:22 UTC, closed without merging