[bitnami/magento] add OpenSearch as a search engine option
bitnami/containers pull request #63946
Opened 2024-03-20 14:13 UTC by vtkstef

### Description of the change

add OpenSearch as a search engine option for Magento. Option `ealasticsearch5 ` and `elasticsearch6` are
no longer supported during setup/bootstrap in magento 2.4.6

### Benefits

OpenSearch has a more permissive open source license (hence the fork from elastic search by amazon) 

### Possible drawbacks

n/a

### Applicable issues

- fixes #63916 

### Additional information

Option `ealasticsearch5 ` and `elasticsearch6` areno longer supported during setup/bootstrap in magento 2.4.6

2024-04-06 01:45 UTC, vtkstef commented
@carrodher FYI can you please reset the timer on this PR. Thanks

2024-04-10 10:58 UTC, mdhont commented
We are going to review this logic internally and we will notify you in this PR when there is any news.
Thank you very much for the contribution!

2024-04-17 02:43 UTC, vtkstef commented
Ping @mdhont

2024-04-22 14:50 UTC, dgomezleon requested changes
Thanks a lot for this contribution. I just added a couple of minor suggestions.

2024-04-22 14:50 UTC, dgomezleon commented on bitnami/magento/2/debian-12/rootfs/opt/bitnami/scripts/libmagento.sh
> +            # Elasticsearch configuration is stored in the database, so we only need to specify for 'setup:install'
```suggestion
            # OpenSearch configuration is stored in the database, so we only need to specify for 'setup:install'
```

2024-04-22 14:50 UTC, dgomezleon commented on bitnami/magento/2/debian-12/rootfs/opt/bitnami/scripts/libmagento.sh
> +            magento_wait_for_es_connection "$oss_host" "$oss_port"
I would rename this function to something generic. E.g. `magento_wait_for_search_engine_connection` or similar.

2024-04-22 14:50 UTC, dgomezleon commented on bitnami/magento/2/debian-12/rootfs/opt/bitnami/scripts/libmagento.sh
> +            info "Trying to connect to Elasticsearch"
```suggestion
            info "Trying to connect to OpenSearch"
```

2024-05-20 10:54 UTC, closed without merging