FIX: Add judge primary node ip port is itslef
bitnami/containers pull request #67370
Opened 2024-05-31 10:40 UTC by kwenzh

### Description of the change

It seems that the judgment of whether the master node IP is your own is missed here.

### Benefits

### Possible drawbacks

### Applicable issues

- fixes #

### Additional information

2024-06-11 07:07 UTC, kwenzh commented
@fmulero @carrodher  please review this  pr

2024-06-27 01:34 UTC, kwenzh commented
1

2024-07-05 11:18 UTC, fmulero requested changes
Hi @kwenzh Sorry about my very late response. I loose this PR from my radar.

I left a little suggestion.

Anyway I'd like to review this change with @rafariossaa because I am not sure about the impact of this change

2024-07-05 11:18 UTC, fmulero commented on bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh
> +           fi
```suggestion
            if  [[ "${upstream_host}:${upstream_port}" = "${REPMGR_NODE_NETWORK_NAME}:${REPMGR_PORT_NUMBER}" ]];  then
                info "Avoid setting itself as primary. Starting PostgreSQL normally..."
            else
                primary_host="$upstream_host"
                primary_port="$upstream_port"
            fi
```

2024-07-15 07:57 UTC, kwenzh commented on bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh
> +           fi
OK just log notice, thank you

2024-07-15 07:59 UTC, kwenzh commented on bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh
> +           fi
@rafariossaa  please look at this

2024-07-31 01:39 UTC, kwenzh commented
refresh

2024-07-31 10:40 UTC, fmulero approved these changes
👍 LGTM

2024-07-31 10:41 UTC, merged