[bitnami/postgresql-pgpool] encrypt health check passwords inside pgp…
bitnami/containers pull request #74021
Opened 2024-10-29 08:42 UTC by yukha-dw

…ool.conf

### Description of the change

Fix password leak `sr_check_password` and `health_check_password` on `pgpool.conf` (by default has `644` permission) using `pg_enc` and `pg_md5`.

### Benefits

Hides `sr_check_password` & `health_check_password`

### Possible drawbacks

No drawback

### Applicable issues

### Additional information

2024-10-31 08:38 UTC, dgomezleon requested changes
Could you please test it using the docker-compose.yaml included in bitnami/pgpool? I executed a quick test building the image with these changes, a using it with the docker-compose. It kept showing these logs:

```
...
pgpool-1  | 2024-10-31 08:35:56.880: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
pgpool-1  | 2024-10-31 08:35:56.882: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
pgpool-1  | 2024-10-31 08:35:57.890: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
pgpool-1  | 2024-10-31 08:35:57.892: main pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
...
```

Also, values for `sr_check_password` and `health_check_password` were empty in pgpool.conf

2024-10-31 08:38 UTC, dgomezleon commented on bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh
> +        debug_execute "${password_encryption_cmd[@]}" "$password" | grep -o -E "AES.+" | tr -d '\n'
This logic is duplicated from `pgpool_generate_password_file`. Could you unify it in a separate function or merge them to avoid code duplication?

2024-10-31 09:21 UTC, yukha-dw commented
@dgomezleon My bad, I've mistakenly put `debug_execute`. It was working fine because I used `BITNAMI_DEBUG=true` when test it

2024-10-31 15:56 UTC, dgomezleon approved these changes
LGTM. Thanks!

2024-10-31 16:01 UTC, merged

2025-02-23 14:54 UTC, ivaylo-mi commented
I don’t think this works correctly when the PGPOOL_AUTHENTICATION_METHOD is md5. According to the pg_md5 documentation the string being hashed must be the password with the username appended to it and the result must be prefixed with md5.