journal doesnt work anymore
bitnami/containers pull request #75699
Opened 2024-12-11 17:12 UTC by jfshark

Same as the https://github.com/bitnami/containers/pull/65826 but for 8 version of mongodb

2024-12-17 15:30 UTC, jotamartos requested changes
Check my comment above

2024-12-17 15:39 UTC, jfshark commented
> Hi @jfshark,
> 
> As that parameter is [no longer supported](https://www.mongodb.com/docs/manual/core/journaling/), could you please update the .sh scripts and remove the mongodb_set_journal_conf function and MONGODB_ENABLE_JOURNAL env var?
> 
> Thanks

Hi @jotamartos,

I would do it, but I am afraid I am not competent enough for this. I simply followed the approach used in [this PR](https://github.com/bitnami/containers/pull/65826), which was accepted and resolved the issue for v7. If there were related changes in another PR or commit, please let me know its ID, and I will incorporate them into my PR as well.

2024-12-17 16:36 UTC, jotamartos commented
The changes are as easy removing these lines (and the entire mongodb_set_journal_conf function) 

```
➜  mongodb git:(main) ag MONGODB_ENABLE_JOURNAL
8.0/debian-12/rootfs/opt/bitnami/scripts/mongodb-env.sh
40:    MONGODB_ENABLE_JOURNAL
126:export MONGODB_ENABLE_JOURNAL="${MONGODB_ENABLE_JOURNAL:-}"

8.0/debian-12/rootfs/opt/bitnami/scripts/libmongodb.sh
493:            if [[ -n "$MONGODB_ENABLE_JOURNAL" ]]; then
494:                mongodb_conf="$(sed -E "/^ *journal:/,/^ *[^:]*:/s/enabled:.*/enabled: $({ is_boolean_yes "$MONGODB_ENABLE_JOURNAL" && echo 'true'; } || echo 'false')/" "$conf_file_path")"

README.md
190:| `MONGODB_ENABLE_JOURNAL`                | Enable MongoDB journal                                                                                                                         | `nil`                               |
355:* `MONGODB_ENABLE_JOURNAL`: Whether to enable/disable journaling on MongoDB&reg;. Default: `true`. Possible values: `[true, false]`
358:docker run --name mongodb -e ALLOW_EMPTY_PASSWORD=yes -e MONGODB_ENABLE_JOURNAL=true bitnami/mongodb:latest
369:      - MONGODB_ENABLE_JOURNAL=true
➜  mongodb git:(main) ag mongodb_set_journal_conf
8.0/debian-12/rootfs/opt/bitnami/scripts/libmongodb.sh
482:mongodb_set_journal_conf() {
1428:    mongodb_set_journal_conf "$MONGODB_CONF_FILE"
```

Can you do that?

2024-12-18 08:49 UTC, jotamartos commented
>I did. But FYI same issue is in mongodb-sharded chart.

Correct, but the mongodb-sharded container shares the same logic with mongodb. Once we merge your changes, mongodb-sharded will be updated too. 

>Also I see the variable MONGODB_DEFAULT_ENABLE_JOURNAL in 8.0/debian-12/rootfs/opt/bitnami/scripts/mongodb-env.sh, which looks somehow related.

Yes, you will need to remove those references too. 

Regarding the issues in the tests, you will find how to solve the DCO test clicking on the Details button.

2025-01-08 02:23 UTC, closed without merging